### ISSUE TITLE
Selekcja ofert pod względem wymaganego czasu dojazdu

### ISSUE THREAD

**Issue by MarcinKosinski** [mi2-warsaw/CzasDojazdu#1]
B) Selekcja lokalizacji
- realizuje Marcin + Tomek + Ola
- zagadnienia: rozkład jazdy ZTM (udostępnia ZTM i jakdojade.pl), trafic API (google raczej nie, ale coś tam jest dostępne), mapy

Pakiet ggmap posłuży (może) to wyciągania podzbiorów obiektów, na podstawie ich lokalizacji, których czas dojazdu jest krótszy od zakładanego od wskazanego przez użytkownika miejsca

> mieliśmy ustawić się na spotkanie w tym tygodniu. Masz jakieś preferencje co do terminu? I w zasadzie o czym będziemy konkretnie gadać, jak się do niego przygotować?

Mam wrażenie, że pakiet ggmap może pomóc nam rozwiązać ten problem. Jestem umówiony w środę z kolegą, który pracował kiedyś z tym pakietem. Moglibyśmy się umówić w czwartek wtedy. Myślę, że do tego czasu warto przeczytać winietke tego pakietu 
https://journal.r-project.org/archive/2013-1/kahle-wickham.pdf
- dodatkowo można przeszukać do tego czasu stackoverflow.com

Założyć można że mierzymy się z problemem: mamy podzbiór współrzędnych na mapie i musimy wybrać te podpunkty, których czas dojazdu od wybranego punktu jest mniejszy niż wymagany przez użytkownika.

@mikolajjj  @abrodecka

**Comment by MarcinKosinski** [comment]
Czy czwartek 18:00 by Wam pasowało się spotkać :)?

**Comment by tmikolajczyk** [comment]
Pasuje. Może być o 18, okolice te co poprzednio - tylko żeby miejscówka bardziej odludna była (ciszej). Czy znasz coś takiego?

**Comment by MarcinKosinski** [comment]
To można uderzyć na politechnikę na wydział matematyki i nauki
informacyjnych (Koszykowa75) :)?

W dniu 8 lutego 2016 23:35 użytkownik mikolajjj notifications@github.com
napisał:

**Comment by abrodecka** [comment]
Mi pasuje :)
9 lut 2016 9:24 AM "Marcin Kosiński" notifications@github.com napisał(a):

**Comment by tmikolajczyk** [comment]
Bardzo chętnie ale czy tam będzie dla nas jakiś przytulny kąt?

**Comment by MarcinKosinski** [comment]
Jest kilka sal ze stołem i krzesłami. Neta mogę puścić z komórki :)

2016-02-09 9:29 GMT+01:00 mikolajjj notifications@github.com:

**Comment by tmikolajczyk** [comment]
Jeżeli możemy tam przebywać - to super; takie miejsce zdecydowanie bardziej nastraja do myślenia niż gwarna kawiarnia. Ja sprawdzę dostępność zaprzyjaźnionego lokalu na Noakowskiego 10 - na wypadek gdyby wyrzucili nas z MiNI

**Comment by MarcinKosinski** [comment]
Z MiNI? Nigdy :)

W dniu 9 lutego 2016 10:12 użytkownik mikolajjj notifications@github.com
napisał:

**Comment by MarcinKosinski** [comment]
To spróbujmy wystartować o 18:00 na MiNI
Możemy się spotkać przy szatni.
Komórkę do mnie macie.

@michalcisek  jak chcesz to wpadaj

**Comment by MarcinKosinski** [comment]
Wrzuciłem przykładowy skrypt, na bazie którego będzie można wyciągąć najbliższe adresy, rysować mapki i zaznaczać punkty na mapce :) moooże się przydać do naszej aplikacji
https://github.com/MarcinKosinski/CzasDojazdu/tree/master/Rscripts/ggmap

**Comment by MarcinKosinski** [comment]
Myślę, że to mamy już opanowane. Więc możemy zamknąć temat.
