### ISSUE TITLE
Panel z wybierz dzielnice

### ISSUE THREAD

**Issue by MarcinKosinski** [mi2-warsaw/CzasDojazdu#12]
@abrodecka  moze ten Panel nie jest potrzebny? Mysle, ze pozostale panele do selekcji ofert w zupelnosci wystarcza do wyfiltorwania danych. Dodatkowo sajdbar po lewej by nam sie skrocil i by sie zmiescily wszystkie guziki :) co sadzisz o tym zeby go usunac? Myslisz, ze dalabys rade?

**Comment by abrodecka** [comment]
Mogę usunąć, myślę że nie powinno być problemu :)
Czy jest potrzebny, sporne pytanie. Jak ktoś szuka czegoś, żeby się
zmieścić w czasie dojazdu to raczej będzie dla niego ważniejsze niż obszary
graniczne dzielnic Warszawy ;)
18 kwi 2016 8:30 PM "Marcin Kosiński" notifications@github.com napisał(a):

**Comment by abrodecka** [comment]
Jutro to zrobię.

W dniu 18 kwietnia 2016 20:33 użytkownik Aleksandra Brodecka <
aleksandrabrodecka@gmail.com> napisał:

**Comment by abrodecka** [comment]
Zrobione.
Można jeszcze skrócić opisy do wybierania na panelu i opisać to na
powitalnej stronie.
I myślę, że przydałby się jakiś screen z mapką albo informacja na pierwszej
stronie, która pokazuje, że można najechać na marker i sprawdzić cenę,
lokalizację i link do oferty bo dla niektórych może to być niejasne :)

W dniu 18 kwietnia 2016 20:49 użytkownik Aleksandra Brodecka <
aleksandrabrodecka@gmail.com> napisał:

**Comment by MarcinKosinski** [comment]
@abrodecka  dzieki! przejrze w domu
W przyszlosci : do tresci commita jak dodasz `tresc #numer_issue` to pojawi sie commit w drzewie tego watku i latwiej bedzie sledzic zmiany :) 
A jakbys chciala skrocic opisy do wybierania na panelu i opisac to na powitalnej stronie? Chetnie to zobacze. Mysle, ze print screen (albo najlepiej gif) bylby dobrym rozwiazaniem

**Comment by abrodecka** [comment]
OK, ok.
Przygotuję to dzisiaj i Ci prześlę ;)

W dniu 19 kwietnia 2016 17:25 użytkownik Marcin Kosiński <
notifications@github.com> napisał:
