### ISSUE TITLE
Informacje na temat autorow w aplikacji

### ISSUE THREAD

**Issue by MarcinKosinski** [mi2-warsaw/CzasDojazdu#13]
Co byście powiedzieli aby do Panelu `Informacje-> Ludzie` dodać takie informacje o nas z podpisana rola w projekcie :) ?
http://bit.ly/1SbHFvK

**Comment by MarcinKosinski** [comment]
@abrodecka  @michalcisek  @mikolajjj what you think?

**Comment by abrodecka** [comment]
Mi odpowiada :)

**Comment by tmikolajczyk** [comment]
jestem za :)

**Comment by MarcinKosinski** [comment]
Okejka, to wyslijcie mi na priva Wasze zdjecia plus adresy do
(niekoniecznie wszystkiego)
- githuba
- linkedina
- twittera
- stackoverflow
- google plus
- maile

2016-04-20 23:14 GMT+02:00 Tomasz Mikołajczyk notifications@github.com:

**Comment by MarcinKosinski** [comment]
![authors](https://cloud.githubusercontent.com/assets/6773454/14866553/9284fb0c-0cc4-11e6-8cee-a9e3d584e1ab.png)

@abrodecka @mikolajjj  @michalcisek póki co mamy taki panel. jest on już dostępny na githubie. jak będę miał normalny dostęp do internetu to wrzucę do naszej aplikacji na serwer. Czy możecie mi podesłać zdjęcia na maila w rozmiarach 400 X 400 pixeli?

**Comment by MarcinKosinski** [comment]
Czy lecimy bez zdjec? Bo nikt mi z Was nie wyslal :< 400 pixeli na 400. Czy mam sobie wziąć Wasze zdjęcia z linkedina?

**Comment by MarcinKosinski** [comment]
Mogą to też być awatary, jak Wam bardziej pasuje :< ale ja swoje zdjecie bym tam wrzuicl :) im wiecej Waszych twarz w necie tym lepiej dla Was

**Comment by tmikolajczyk** [comment]
coś podeślę przez weekend

Pozdr
Tomek

2016-04-29 13:37 GMT+02:00 Marcin Kosiński notifications@github.com:
