### ISSUE TITLE
Problem z datą w danych - dlatego nie mamy danych na serwerze

### ISSUE THREAD

**Issue by MarcinKosinski** [mi2-warsaw/CzasDojazdu#14]
Michał czy mógłbyś opisać problem, tak żeby wszyscy wiedzieli @michalcisek 

CC @mikolajjj  @abrodecka

**Comment by michalcisek** [comment]
Nie mamy aktualnych ofert, ponieważ do bazy danych nie jest wgrywana data dodania ogłoszenia. Ręcznie jak przechodzimy przez skrypt to poprawnie jest scrapowana ta zmienna. Być może problem leży w formacie. Sprawdzę i dam znać.

**Comment by michalcisek** [comment]
Okej, problem jest z polskimi znakami występującymi w nazwie miesięcy. Przez to przy konwersji na datę, zwraca brak danych

**Comment by MarcinKosinski** [comment]
Mamy pomysł jak to naprawić?

W dniu 29 kwietnia 2016 18:27 użytkownik Michał Cisek <
notifications@github.com> napisał:

**Comment by michalcisek** [comment]
Tak, poprawię to.

**Comment by MarcinKosinski** [comment]
@mikolajjj - dlatego nie mieliśmy żadnej oferty w danych do prezentacji, bo zadna nie miala daty.

**Comment by MarcinKosinski** [comment]
@michalcisek sprawdzalem pobieranie danych dla gumtree :
https://gist.github.com/MarcinKosinski/d197195d849977d9d16eb3ec68425fb9

to data pobiera sie okej (nie ma polski znakow w datach, bo data jest numeryczna). 
Czy moglbys jakos lepiej zobrazowac problem, bo nie widze gdzie ewentualnie szukac, zeby cos pomoc?

**Comment by michalcisek** [comment]
@MarcinKosinski problem jest dla olx-a. Tam data pobierana jest przykładowo z wyrażenia "Dodane o 17:12, 16 kwietnia 2016". Po obróbce, "kwietnia" jest zamieniane na "kwiecień", które zawiera polski znak i rodzi się problem. Trzeba po prostu zmienić, żeby podstawiał liczbę i będzie po kłopocie.

**Comment by michalcisek** [comment]
Poprawiłem, powinno być okej.
