### ISSUE TITLE
Outliers'y w cenach ofert

### ISSUE THREAD

**Issue by tmikolajczyk** [mi2-warsaw/CzasDojazdu#15]
Jak odfiltrować oferty z pseudo-cenami? Mamy np. coś takiego:
cena  adres
509569099 Kopalniana, Warszawa, Polska
69999 Białostocka 
58333 Tomcia Palucha 
5000 NA                  

Są też takie oferty, gdzie cena jest poniżej 100. 

Wiem, że można ręcznie odfiltrować ceny-nieceny, ale dobrze byłoby mieć mechanizm, który zrobi to automatycznie. W jednym z [kodów](https://github.com/mi2-warsaw/CzasDojazdu/blob/master/Rscripts/wykresy/mapa_srednich_cen.R) (linia 14) podjąłem próbę, ale efekt był niezadowalający. Ktoś spróbuje?

**Comment by MarcinKosinski** [comment]
@mikolajjj to moze 

``` R
filter(cena > 500) %>%
filter(cena < 5000) %>%
```

?

**Comment by tmikolajczyk** [comment]
to co zaproponowałeś to jest rozwiązanie ręczne. tak to też potrafię ;)

**Comment by MarcinKosinski** [comment]
To może po kwantylach?

``` R
filter(cena > quantile(cena, 0.01) %>%
filter(cena < quantile(cena, 0.99) %>%
```

to jest automatyczne :P? jest tyle samo pisania

**Comment by tmikolajczyk** [comment]
tak jest teraz. przy parametrach, które podałeś, w bazie na z dzisiaj, odfiltrowujesz ok. 60 ofert z przedziału do 2500 (prawdziwych) i nie odfiltrowujesz pozostałych ofert z pseudo-cenami (16, 17, 70 zł, itd.). to oczywiście jest prawdziwe przy dzisiejszym stanie bazy. jak wpadnie kolejne 10k ofert to powyższe kwantyle zwrócą inne podzbiory

**Comment by MarcinKosinski** [comment]
I co teraz możemy zrobić w takiej sytuacji :)?
Mamy dwa rozwiązania: kwantylowe + za'hard'kodowane.
Musimy pójść na jakiś kompromis. Takich kompromisowych decyzji przy
analizie danych podejmuje się codziennie setki i nie ma się co długo nad
tym zastanawiać.

Ja proponuje
- zahardkodowane : 500 < x < 5000
- kwantylowe q(0.02) < q(0.999) - albo inne kwantyle, które Mikołaj może by
  chciał zaproponować?

Ale to dalej jest wszystko ręczne :P nie wiem jak mogłaby tu zadziałać
automatyzacja

W dniu 6 maja 2016 09:36 użytkownik Tomasz Mikołajczyk <
notifications@github.com> napisał:

**Comment by tmikolajczyk** [comment]
wybieram rozwiązanie "ręczne" zahardkodowane  :)
ale czuję, że da się to sprytniej zakodować. w przyszłości, a tymczasem zamykam temat

**Comment by MarcinKosinski** [comment]
To może jakieś pytanie na stackoverflow? Może są jakies techniki
wyszukiwania outlierów?
http://www.r-bloggers.com/a-tutorial-on-outlier-detection-techniques/
https://cran.r-project.org/web/packages/outliers/outliers.pdf

2016-05-06 10:20 GMT+02:00 Tomasz Mikołajczyk notifications@github.com:
