### ISSUE TITLE
Przecinki w cenach

### ISSUE THREAD

**Issue by tmikolajczyk** [mi2-warsaw/CzasDojazdu#17]
@michalcisek 

w ofertach z OLX znika przecinek z ceny i generuje ceny "z kosmosu" (powinno zamienić na kropkę)

przykład. dla tej oferty: http://olx.pl/oferta/duzy-pokoj-dla-pary-lub-trzech-osob-pkp-wlochy-ul-nastrojowa-14-CID3-IDdDNLz.html#7ebaf6a07a cena w naszej bazie to 49999

poprawiłem w Twoim kodzie. mam nadzieję, że jest ok

**Comment by tmikolajczyk** [comment]
@michalcisek odwróciłem zmianę. mam prośbę - zmodyfikuj swój kod, tak, żeby w cenie odcinało wszystkie wartości po przecinku (jeśli występują)

**Comment by MarcinKosinski** [comment]
@mikolajjj robiac commita, mozesz do tresci wpisac ' #numer_issue tress_commita' - wtedy w drzewie issue pokaza sie commity ktore robiles w ramach tego watku. Ulatwi to zycie i przegladanie commitow :) a czemu cofnales zmiane?

**Comment by tmikolajczyk** [comment]
@MarcinKosinski - ok. postaram się to ogarnąć
cofnąłem zmianę ponieważ nie przyniosła efektów (widziałem, że @michalcisek robi coś jeszcze z ceną na końcu kodu). uznałem, że nie będę głębiej grzebał i poproszę Michała o zmiany

**Comment by MarcinKosinski** [comment]
Poprawilem. Na githubie widac w drzewie, ze zamknalem ten temat z commit'a w ktorego wiadomosci uwzglendilegm '#17' - mysle, ze teraz sie dobrze powinny logowac ceny :)

https://github.com/mi2-warsaw/CzasDojazdu/commit/cad3368a1e09cef871560a8c1c2b96abf01bada7

**Comment by tmikolajczyk** [comment]
jeśli najświeższe dane są po tej po poprawce, to nie działa. nadal mam w Mokotowie ofertę za 49999 a na Pradze za 69999. a z tej oferty: http://www.gumtree.pl/a-pokoje-do-wynajecia/wola/duzy-ppkoj-dla-1-osoby/1001628982680910656518009 robi sieczkę (cena: 509569099)

**Comment by MarcinKosinski** [comment]
A z jakiej daty jest ta oferta w naszej bazie danych a którego dnia była
wprowadzona poprawka? Nie poprawiałem wcześniejszych ofert. Może by uciąć
oferty i zacząć je zbierać od nowa, bez ofert z OLX, które nie mają adresów
i wielkości pokoi, co jest problematyczne lekko i kiepsko wygląda?

2016-05-16 13:03 GMT+02:00 Tomasz Mikołajczyk notifications@github.com:
