### ISSUE TITLE
Wyfiltorwać oferty wykraczające geograficznie poza Warszawę

### ISSUE THREAD

**Issue by MarcinKosinski** [mi2-warsaw/CzasDojazdu#19]
tak, żeby nie mieć niepotrzebnie za dużo danych + żeby na mapę nie nanosiły się miejsca z morza :P

```
północ: 52.368653
południe: 52.098673
wschód: 21.282646
zachód: 20.851555
```

**Comment by tmikolajczyk** [comment]
a współrzędne biorą się skąd?

2016-05-11 22:46 GMT+02:00 Marcin Kosiński notifications@github.com:

**Comment by MarcinKosinski** [comment]
Współrzędne biorą się przy scrapowaniu np tu https://github.com/mi2-warsaw/CzasDojazdu/blob/master/Rscripts/collect_data/002_gumtree_scraping.R#L111

No i czasami mamy kiepski adres, albo mamy e-mail w adres i znajduje wspolrzedne z kosmosu. I ja je bym filtrowal w momencie ladowania apki tu

https://github.com/mi2-warsaw/CzasDojazdu/blob/master/App/app.R#L27
