### ISSUE TITLE
Wyciąganie informacji o adresie z opisu bądź tytułu oferty 

### ISSUE THREAD

**Issue by MarcinKosinski** [mi2-warsaw/CzasDojazdu#2]

**Comment by MarcinKosinski** [comment]
@abrodecka przygotowała super skrypty tutaj:  https://github.com/MarcinKosinski/CzasDojazdu/blob/master/Rscripts/ulice/ulice.R

Przyda się jeszcze wrzucić plik z wykazem wszystkich ulic?
Wtedy ja na przykładzie, który dzisiaj pokazywałaś mógłbym przygotować przerobienie odmian nazw ulic użytych w opisie na prawdziwą nazwę tej ulicy :)?

**Comment by MarcinKosinski** [comment]
@abrodecka  dodałem mały modyfikator w Twoim skrypcie, tak że umiemy teraz wyczaić adres gdy ktoś napisze `ul Dywizjonu 303` - bez kropki po `ul` albo `al` :) commit powyżej

**Comment by abrodecka** [comment]
Ok, ok ;)
chyba oszukiwałeś, że nie pamiętasz regexów :)
13 lut 2016 10:40 PM "Marcin Kosiński" notifications@github.com
napisał(a):

**Comment by MarcinKosinski** [comment]
Swoją drogą obczaj przykład tego jak znaleźć z `odmiany ulicy` najbliższą jej formę z danego zbioru propozycji

``` R
# install.packages('stringdist')
library(stringdist)



potencjalne_adresy <- c("Żeromskiego",
                        "Żiżki",
                        "Żonkilowa",
                        "Żołnierska",
                        "Żołny",
                        "Żółkiewskiego")

dict_dists <- stringdist(c("Żołnierskiej"),potencjalne_adresy)

potencjalne_adresy[which.min(dict_dists)]

```

**Comment by MarcinKosinski** [comment]
@abrodecka  nie pamiętam, przerobiłem Twój, w którym miałaś
`(ul\\.|al\\.)` na `(ul|al\\s)` :) tyle jeszcze rozumiem z regexów. Ale Twoje są dumne. Sama pisałaś od podstaw czy się czymś inspirowałaś?

**Comment by abrodecka** [comment]
Tylko i wyłącznie wykładem Gągolewskiego :)
Jutro, na spokojnie popatrzę na tę odmianę ulic.
13 lut 2016 11:05 PM "Marcin Kosiński" notifications@github.com
napisał(a):

**Comment by MarcinKosinski** [comment]
Już zaimplementowałem do bazy danych, tak że wyciągajac opis ogłoszenia, od razu wyciągamy Twoim sposobem adres, a moim najbardziej poprawną wersję adresu. Więc już spokojnie można próbowac pisać apke shiny :)

**Comment by tmikolajczyk** [comment]
Dodałem alternatywną metodę pozyskania listy ulic. Dane pobieramy z API UM Warszawy. Wypluwa dość dużą listę, z którą niestety nie potrafię sobie dalej poradzić (może ze względu na porę dnia). Wrzucam, bo te dane wydają się obiecujące bo zawierają odmienione nazwy ulic. Zerknijcie na to i oceńcie czy jest sens w tym dalej grzebać.

Ps. nie wiem dlaczego nie wrzuciło tego z mojego profilu, więc spróbuję za chwilę to jeszcze raz dodać, już pod swoim profilem

**Comment by MarcinKosinski** [comment]
Wrzuciło z domyślnego profilu bo nie masz skonfigurowanego githuba lokalnie:
https://help.github.com/articles/set-up-git/

W dniu 14 lutego 2016 01:43 użytkownik Tomasz Mikołajczyk <
notifications@github.com> napisał:

**Comment by MarcinKosinski** [comment]
Widzę, że w Twoim zbiorze są odmienione nazwy ulic, ale sa one tylko w
poprawnej polszczyźnie (uwzględniają polskie znaki). Póki co nasza metoda
wyciąga z opisu wszystko co występuje po frazach `ul / ul. /al. / al /
ulicy` itp. a następnie dla nazw wszystkich ulic, które pobieramy ze
strony, którą pokazała Ola staramy się znaleźć najbliższą nazwę.

Równie dobrze można odwoływać się do Twojego zbioru i po zmatchowaniu słowa
odwoływać się do jego formy podstawowej, albo do jego współrzędnych.

Insza inszość, że zbiór, który proponujesz zadziała tylko w warszawie i nie
będzie uniwersalny w obrębie całej polski.

W dniu 14 lutego 2016 01:51 użytkownik Marcin Kosiński <
m.p.kosinski@gmail.com> napisał:

**Comment by tmikolajczyk** [comment]
Marcin, chętnie zobaczę kod jakim przekopałeś się przez te dane z API

**Comment by MarcinKosinski** [comment]
Którego API? 

Ogolnie cos Dzis wrzucałem (historia 3 ostatnich moich commitow), ale robiłem niezależnie od Twoich danych. 

W sumie to co poki co mamy, co dziala, to zadziała tez tylko dla Warszawy :p

Marcin Kosinski

Dnia 14.02.2016 o godz. 02:04 Tomasz Mikołajczyk notifications@github.com napisał(a):

**Comment by MarcinKosinski** [comment]
Punkty jeszcze mozesz dostać za zadawanie pytań 

Marcin Kosinski

Dnia 14.02.2016 o godz. 02:04 Tomasz Mikołajczyk notifications@github.com napisał(a):

**Comment by abrodecka** [comment]
Myślałam nad wyciąganiem nazw ulic z opisów i tak się zastanawiam:
1) Dlaczego nie korzystamy z pobierania adresu od razu z htmla? Np. opis tego ogłoszenia nic nam nie mówi o dokładnej lokalizacji ale widzimy adres w prawym okienku; http://www.gumtree.pl/a-pokoje-do-wynajecia/targowek/pokoj-w-90-metrowym-mieszkaniu-z-balkonem-na-poddaszu/1001582814330910663247609 
2) Niektórzy w ogłoszeniu podają wyrażenia typu: 5 min od Metra Kabaty, 10 min od przystanku Banacha itd. Mogłabym spróbowac wyciągać takie informacje i potem na mapie zaznaczać lokalizację takiego przystanku, innym kolorem markera i np. w popup'ie dodać informację: "5 min od Metra Kabaty". Tylko zastanawiam się nad sensem takich lokalizacji jak nie możemy wybrać komunikacji miejskiej w mapdist :)

**Comment by MarcinKosinski** [comment]
Co do 1)

Faktycznie jesteśmy gapy, że nie scrapujemy informacji spod obrazka z mapą,
tylko kombinujemy. @michalcisek co Ty na to? SelectorGadget podpowiada, że
jest tag w HTMLu: ".address" :)))) pięknie Ola

2) To by było ciężkie. Myślę, że samo to, że leaflet ma dodatkowe
informacje o wgranych miejscach dotyczących kawiarni, przystanków itp już
powinno wystarczyć.

W dniu 1 marca 2016 23:39 użytkownik abrodecka notifications@github.com
napisał:

**Comment by michalcisek** [comment]
Nie zwróciłem nawet uwagi, że jest takie pole. Zaraz poprawię :))

**Comment by MarcinKosinski** [comment]
A człowiek sie nakombinowal :)

Marcin Kosinski

Dnia 04.03.2016 o godz. 15:06 Michał Cisek notifications@github.com napisał(a):

**Comment by MarcinKosinski** [comment]
Chyba nieaktualne od kiedy mamy normalnie adres z ofert :P
Zamykam
