### ISSUE TITLE
Mapa ze statystykami per dzielnica

### ISSUE THREAD

**Issue by MarcinKosinski** [mi2-warsaw/CzasDojazdu#25]
@mikolajjj dorzucam Twoją mapę.

Powiedz jakimi danymi powinna być zasilana, co jaki czas dane powinny być aktualizowane i ewentualnie jakie dane chcemy tu prezentować jeszcze?

**Comment by tmikolajczyk** [comment]
Chwilowo temat zawieszamy, do czasu aż poprawię tę mapę, żeby się zawsze wyświetlała

**Comment by MarcinKosinski** [comment]
To trzeba wywalić te niepotrzebne biblioteki

2016-05-31 22:42 GMT+02:00 Tomasz Mikołajczyk notifications@github.com:

**Comment by MarcinKosinski** [comment]
Na koncu pliku

**Comment by MarcinKosinski** [comment]
To dziala u nas w aplikacji bo aplikacja wspierana jest przez shiny server i wszystkie obliczenia dzieja sie po stronie serwera. Nie bedzie to zawsze dzialalo jako niezalezna strona internetowa, bo wtedy wczytanie danych i stworzenie tej mapy to obliczenia ktore musza wykonac sie w (UWAGA sic!) przegladarce :P
