### ISSUE TITLE
Angielska wersja aplikacji

### ISSUE THREAD

**Issue by MarcinKosinski** [mi2-warsaw/CzasDojazdu#26]
@wchodor 

W folderze `App` stworzyć folder `en` z angielską wersją aplikacji. Skopiować wszystkie pliki z `App` do `en`.

Do zmiany/przejrzenia byłyby
- app.R
- elements/
  - header -> naglowek/pasek na gorze
  - sidebar -> po lewej [ja tutaj na sam koniec Twojej roboty dodam link do przenoszenia miedzy polska a angielska wersja storny]
  - body -> cale cialo aplikacji

**Comment by MarcinKosinski** [comment]
@wchodor  robiąć commity, możesz w treści commita dawać `tresc #26` - wtedy w drzewie tego issue pojawi sie historia commitow wspominajacych to zadanko

**Comment by wchodor** [comment]
@MarcinKosinski , czy w dobrych miejscach wstawiłem tłumaczenia ?

**Comment by MarcinKosinski** [comment]
@wchodor umieszczam po kolei commity ze sprawdzeniem :P
niestety w aplikacjishiny plik `app.R` i folder `www` musza sie tak nazywa i nie moga miec innego rozszerzenia

**Comment by MarcinKosinski** [comment]
Niestety zapominam dodawac `#26` do commitow :P i tylko niektore tu wpadaja

**Comment by MarcinKosinski** [comment]
@mikolajjj  @abrodecka @michalcisek mamy wersje 
- polska pod nowym adresem: http://mi2.mini.pw.edu.pl:3838/CzasDojazdu/pl/
- angielska : http://mi2.mini.pw.edu.pl:3838/CzasDojazdu/en/
