### ISSUE TITLE
Podrasowanie dashboard'u

### ISSUE THREAD

**Issue by tmikolajczyk** [mi2-warsaw/CzasDojazdu#28]
np. na taki: http://demos.creative-tim.com/light-bootstrap-dashboard/dashboard

**Comment by MarcinKosinski** [comment]
tego sie chyba nie da w tak oczywisty sposob podpiac pod shiny bo tutaj kazda czesc dashboardu to oddzielny css a do shajniakowego dashboardu mozna dodac cssy odpowiedzialne za wyglad czcionek a nie za wyglad paneli ;/
