### ISSUE TITLE
Scrapowanie danych

### ISSUE THREAD

**Issue by krzyslom** [mi2-warsaw/CzasDojazdu#31]
Cześć,

przeglądając scrapera natknąłem się na parę rzeczy do poprawy:

1. Wielkość mieszkania nie zawsze znajduje się pod css li:nth-child(8) .value. W zależności od ilości podanych parametrów w ofercie pozycje konkretnych atrybutów zmieniają się.

2. Brak kolekcjonowania informacji o preferowanej płci, czy pokój jest dla osoby palącej itp.

3. keys<-c("szukam", "Szukam", "Poszukuje", "poszukuje", "Poszukuję", "poszukuję") ignoruje wyrazy pisane w całości wersalikami.

4. Zapisywany jest link tylko do pierwszego zdjęcia. Czy potrzebne są do pozostałych?

5. Po co jest kolumna content?

Na obecną chwilę udało mi sie poprawić 1-3. Pytanie co zrobić z 4 oraz 5.

W celu umieszczenia wszystkich atrybutów oferty należy dodać do struktury tabeli w bazie danych kolumny o następujących nazwach: dostepny, do_wynajecia_przez, liczba_pokoi, palacy, preferowana_plec, przyjazne_zwierzakom, rodzaj_nieruchomosci, wspoldzielenie.

Czy z punktu widzenia użyteczności aplikacji jest sens uzupełniać bazę danych o brakujące wielkości?

**Comment by MarcinKosinski** [comment]
@michalcisek do Twojej wiadomosci - Krzysiu w #32 wprowadza zmiany

co do 4 - niepotrzeba wiecej zdjec
co do 5 - to jest tresc ogloszenia chyba :)? do dalszej analizy tekstu : ) ?
