### ISSUE TITLE
Pokazywanie danych w zakładce Dane

### ISSUE THREAD

**Issue by krzyslom** [mi2-warsaw/CzasDojazdu#39]

**Comment by MarcinKosinski** [comment]
A nie ma jakiejś zakładki z Tabela? Swoją droga do tej tabeli można dodać linki do ofert w którejś z kolumn :)

**Comment by krzyslom** [comment]
Tabela była, teraz zarówno przy pustej jak i wypełnionej korzysta ona z funkcji wyciągniętej do pliku app/funkcje.R Dzięki temu jej reprezentacja jest ujednolicona (teraz są ładniejsze nazwy kolumn i hiperłącza).

**Comment by MarcinKosinski** [comment]
Elegancko, jak się udało, to możesz zamknąć to zadanie, żeby tu lekko uporządkować.
