### ISSUE TITLE
Autorzy w header notifications.

### ISSUE THREAD

**Issue by krzyslom** [mi2-warsaw/CzasDojazdu#40]
Wszyscy autorzy widnieją w sidebar -> O projekcie -> Ludzie (swoją drogą trzeba zmienić na Autorzy). W związku z tym może usunąć poszczególne osoby z header -> notifications i zostawić tam tylko przekierowanie do repozytorium, do grupy wCZASowicze oraz informację o aktualnym stanie danych?

**Comment by MarcinKosinski** [comment]
Jestem za
