### ISSUE TITLE
aplikacja shiny versja 1: statyczna

### ISSUE THREAD

**Issue by MarcinKosinski** [mi2-warsaw/CzasDojazdu#5]

**Comment by abrodecka** [comment]
Dzisiaj ustalaliśmy jak ma wyglądać apikacja shiny. Stwierdziliśmy, że użytkownik będzie mógł wybrać:
- dzielnicę miasta
- maksymalny czas dojazdu
- środek transportu
- przedział cenowy
- rodzaj lokalu (mieszkanie, pokój itp.)
  Na razie wszystkie oferty spełniające warunki użytkownika mają pojawiać się na mapie (Nie rysujemy tras przejazdu)

**Comment by tmikolajczyk** [comment]
wrzuciłem dane do testowania aplikacji Shiny (jeśli powstanie wcześniej niż pobierzemy i przetworzymy prawdziwe dane). bazowałem na kodzie Michała. [tu jest mój kod](https://github.com/MarcinKosinski/CzasDojazdu/blob/master/Rscripts/shiny_test/dane_test_shiny.R). bezczelnie usunąłem rekordy bez ulicy oraz dwa ogłoszenia z Wesołej :)

ponieważ potrzebowałem do zestawienia dzielnic to poszperałem w necie i znalazłem kompletne zestawienie warszawskich ulic, placów, skwerów .... jest tam absolutnie wszystko (5300 rekordów) i udostępnia to UM więc jest aktualne. w folderze "dicts" jest plik z tymi danymi (wawa_obiekty.csv) a kod którym poczyściłem pobrane dane (można pobrać tylko XLS) jest [tutaj](https://github.com/MarcinKosinski/CzasDojazdu/blob/master/Rscripts/ulice/obiektyWawa.R)

mam nadzieję, że do czegoś się to przyda

**Comment by abrodecka** [comment]
Dzięki, na pewno skorzystam ;)
17 lut 2016 10:18 PM "Tomasz Mikołajczyk" notifications@github.com
napisał(a):

**Comment by MarcinKosinski** [comment]
Czesc,

Moze chcemy sie spotkac w ten czwartek i opracowac ta aplikacje?
Nawet jak nie umiemy za duzo to sie nauczymy i ja zrobimy :)

**Comment by abrodecka** [comment]
Tak, miałam się odezwać :) ja już coś tam działałam, postaram się wieczorem
wstawić kody. Mam taki mały problem przy jednoczesnym wyborze kilku
dzielnic, mam nadzieję że go rozwiążemy w czwartek :)
23 lut 2016 12:09 PM "Marcin Kosiński" notifications@github.com
napisał(a):

**Comment by MarcinKosinski** [comment]
Extra :) 

Marcin Kosinski

Dnia 23.02.2016 o godz. 12:13 abrodecka notifications@github.com napisał(a):

**Comment by MarcinKosinski** [comment]
Jutro o 18:00 by Ci pasowało? Czy wolisz 16/17? 
Kafe Cofeina na polnej (obok subwaya), na przeciwko gmachu głównego politechniki by Ci odpowiadało?

**Comment by abrodecka** [comment]
Dostosuję się do Ciebie. Mi pasuje zarówno 18 jak i nieco wcześniej. :)
24 lut 2016 8:44 PM "Marcin Kosiński" notifications@github.com napisał(a):

**Comment by MarcinKosinski** [comment]
17:30 cafe coffeina? Bede na miejscu, ale jakbyśmy mieli sie nie znalezc to moj kom 503 435 652

Marcin Kosinski

Dnia 24.02.2016 o godz. 21:09 abrodecka notifications@github.com napisał(a):

**Comment by abrodecka** [comment]
Ok. Tu masz mój numer 535 653 790 w razie problemów :)
25 lut 2016 1:35 AM "Marcin Kosiński" notifications@github.com napisał(a):
