### ISSUE TITLE
Obrysy dzielnic i mapa warszawy | zmiana nazwy

### ISSUE THREAD

**Issue by tmikolajczyk** [mi2-warsaw/CzasDojazdu#6]
Wrzuciłem kod tworzenie obrysów Warszawy (folder mapa) i przykładowy efekt.
Dodatkowo, w 'dicts' zestawienie kodów polskich gmin z bazy TERYT. To było konieczne do zdekodowania nazw dzielnic i może przydać się w przyszłości

**Comment by MarcinKosinski** [comment]
Swietnie dzieki!

Umawiamy sie na jakis dzien, zeby przygotowac przykladowe analizy z danych?

**Comment by tmikolajczyk** [comment]
Jak najbardziej. Niestety nie mogę umawiać się na ten tydzień, bo być może będę wyjeżdżał na przedłużony weekend już w czwartek a jutro odpada. Odezwę się

**Comment by MarcinKosinski** [comment]
Cytuje Tomasza

> Hej Marcin,
> 
> wrzuciłem dzisiaj kod ze zmodyfikowaną mapą dzielnic (naniesione etykiety i ceny dla dzielnic). Mógłbyś rzucić okiem na ten kod? Coś mi straszenie muli komp a czcionki wychodzą jakieś takie brzydkie. Robiłem to w pracy i tam wyglądało ok. 
> 
> Pozdrawiam
> Tomek

@abrodecka @michalcisek

**Comment by MarcinKosinski** [comment]
Zamykamy ten issue czy jeszcze cos tu jest do zrobienia mikolajj? Moze to przemianowac na `wykresy do analiz` ?feel free

**Comment by tmikolajczyk** [comment]
zamykamy

a co chcesz przemianować?

**Comment by MarcinKosinski** [comment]
mozna zmienic nazwe (widac w drzewie na githubie, ze zmienila sie nazwa)

**Comment by MarcinKosinski** [comment]
closed with https://github.com/mi2-warsaw/CzasDojazdu/commit/ea6654f747b37e5900d098627de0b1392fe943af
