### ISSUE TITLE
Publicznosc kodow

### ISSUE THREAD

**Issue by MarcinKosinski** [mi2-warsaw/CzasDojazdu#7]
Co byscie powiedzieli na upublicznienie kodow i praca z publiczym repozytorium?

@michalcisek @abrodecka @mikolajjj

**Comment by MarcinKosinski** [comment]
Czy dopiero jak dokonczymy wsio :)?

**Comment by michalcisek** [comment]
@MarcinKosinski jak dla mnie możemy udostępnić :)

**Comment by abrodecka** [comment]
@MarcinKosinski https://github.com/MarcinKosinski Możemy udostępnić :)

W dniu 29 lutego 2016 10:11 użytkownik Michał Cisek <
notifications@github.com> napisał:

**Comment by MarcinKosinski** [comment]
Musialem i tak udostpenic, bo mi sie konczyla studencka znizka 2letnia :)
Przy okazji przenioslem repozytorium na organizacje mi2, do ktorej dostaliscie zaproszenia :)
