### ISSUE TITLE
Testowanie i uzupełnianie aplikacji

### ISSUE THREAD

**Issue by MarcinKosinski** [mi2-warsaw/CzasDojazdu#9]
@abrodecka  @mikolajjj  @michalcisek 

Czołem ancymony! 

Przepraszam za mały dilej (delay), ale ostatnio miałem za dużo okazji do świętowania, a za mało do devel'owania :) 
Znalazłem wolniejszą chwilę i pozwoliłem sobie lekko poprawić aplikację Aleksandry i przerobiłem ją na [shinydashboard](https://rstudio.github.io/shinydashboard/)

jest dostępna pod tym adresem http://mi2.mini.pw.edu.pl:8080/CzasDojazdu/App/

Nie wszystkie pola są uzupełnione i nie wszystkie elementy jeszcze umieściłem w aplikacji, ale póki co prosiłbym Was abyście przetestowali czy aplikacja się sprawdza, czyli:
- Czy panel po lewej jest dobrze rozmieszcozny? A może guzik 'Pokaż lokalizację' powinien być na górze? Czy takie wskaźniki wyboru są wystarczające?
- Czy aplikacja nie sypie nieokreślonymi błędami, na które nie jesteśmy odporni? Jeżeli tak to prosiłbym o print screeny z zaznaczonymi dzyndzlami na panelu z ustawieniami i z komunikatem błędu.
- Moglibyście pokazać aplikację kilku znajomym i spytać czy jest dla nich czytelna.
1. W międzyczasie moglibyśmy zastanowić się nad uzupełnieniem panelu `O projekcie` - jeżeli chcecie mogę się tym zająć, ale chętnie przyjmę wszelki uwagi i propozycje.
2. Czy chcemy aplikacje rozszerzać aby udostępniała dane o mieszkaniach? Póki co mamy same pokoje.
3. Nie dodawałem jeszcze wykresów Mikołaja z potencjalnymi analizami.
4. Zakładka dane udostępnia tabele z obecnie wybranymi danymi. Czy chcemy ją lepiej opisać, np. tekstem nad nią?

Jestem bardzo zadowolony z tego jak wygląda i jak działa ta aplikacja :) zdolniachy z Was

**Comment by MarcinKosinski** [comment]
Błąd numer jeden (ale to chyba wina przeglądarek/ustawień serwera/wersji shiny) - na aplikacji nie widać ikonki przy mieszkaniach a lokalnie na laptopie ją widać.
Korzystamy z tych czcionek https://fortawesome.github.io/Font-Awesome/icons/ , więc może chcielibyśmy ją zamienić na jakąś inną? Może ona jest za nowa na stary shiny-server na mi2?

![blad_nr_1](https://cloud.githubusercontent.com/assets/6773454/14541624/2393e39a-028b-11e6-960e-f71a0d780d24.png)

**Comment by MarcinKosinski** [comment]
Pierwszy komć od mojej koleżanki

> docelowy rozumiem poprzez miejsce gdzie to moje spanie sie znajduje zeby mi sie wyswietlilo a nie zebym sobie wpisala xD
> a myslisz ze czym przesunęlam do tego momentu Emotikon tongue
> o ciekawe teraz dziala
> moze sie cos przycielo
> co do suwaka czasu wydaje mi sie ze wytypowanie co do minuty jest niepotrzebne a przez to mniej wygodne
> może jakas podzialka max co 5 min
> Wybierz dzielnicę:
> to się tyczy miejsca gdzie się znajduję czy gdzie chcę znalezc miejscowe?
> generalnie na pierwszy rzut oka nie wiedząc co dokladnie mieliscie na mysli robiąc to jest  dla mnie niezrozumiałe
> a planujecie wprowadzic parametry typu jaki pokoj tzn ilu osobowy albo na jak długo jest wolny?

**Comment by abrodecka** [comment]
Zebrałam kilka uwag:
1) Pole dzielnica: Trzeba pozmieniać Praga-Południe na Praga Południe itp.
2) Po wybraniu ofert nie pokazuje się zbyt dużo lokalizacji, nie wiem czy
to kwestia usuwania wszystkiego co nie puste. Na przykład, dla Ochoty i
maksymalnego czasu dojazdu i cenu pokoju powinno pokazać nam się wszystkie
lokalizację. Pokazują się tylko 4.
3) Pasek jest za długi i ciężko nacisnąć pokaż lokalizację po wybraniu
kilku dzielnic
4) Po wybraniu "pokaż lokalzację" mapa pokazuje bardzo oddaloną mapę
Warszawy
5) Po schowaniu paska po lewej nie można wrócić do niego wrócić, tak ma
zostać?

W dniu 14 kwietnia 2016 22:32 użytkownik Marcin Kosiński <
notifications@github.com> napisał:

**Comment by MarcinKosinski** [comment]
Bardzo ciekawe komcie :) na pewno sie przydadzą. Co do ostatniego to wydaje mi sie, ze da sie wrócić 

Marcin Kosinski

Dnia 14.04.2016 o godz. 23:36 abrodecka notifications@github.com napisał(a):

**Comment by MarcinKosinski** [comment]
Mielismy maly feedback, po ktorym @abrodecka zdecydowala sie dodac do strony glownej instrukcje 

![intro](https://cloud.githubusercontent.com/assets/6773454/15054433/c484c832-1307-11e6-86ac-70de55d825bc.png)
- panel po lewej lekko skrocony zostal. Gdyby ktos jeszcze mial pomysly w sprawie polepszenia tej aplikacji to mozna otworzyc ten watek z wpisem o nowych pomyslach
